# Generated by Django 6.1.1 on 2026-10-06 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerkaraYudisial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_perkara', models.CharField(max_length=100, unique=True)),
                ('judul_kasus', models.CharField(max_length=255)),
                ('jenis_perkara', models.CharField(choices=[('PIDANA', 'Pidana'), ('PERDATA', 'Perdata'), ('NARKOTIKA', 'Narkotika / FILM-Rehabilitasi')], default='PIDANA', max_length=20)),
                ('l1_fakta_dasar', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('l5_keraguan_pengujian', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('l6_konsistensi_logika', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('l7_validasi_metode', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10)])),
                ('l11_konklusi_putusan', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('l12_keadilan_sosial', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('nilai_e', models.FloatField(blank=True, null=True)),
                ('zona', models.CharField(blank=True, max_length=50)),
                ('catatan_analisis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
